CREATE TABLE IF NOT EXISTS USER_ACCOUNTS (
    ID BIGSERIAL PRIMARY KEY,
    USER_ID VARCHAR(100) NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL
);