CREATE TABLE IF NOT EXISTS CATEGORIES (
    ID BIGSERIAL PRIMARY KEY,
    CATEGORY_ID VARCHAR(100) NOT NULL,
    USER_ID VARCHAR(100) NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(100)
);