CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    ID BIGSERIAL PRIMARY KEY,
    TRANSACTION_ID VARCHAR(100) NOT NULL,
    CATEGORY_ID VARCHAR(100) NOT NULL,
    USER_ID VARCHAR(100) NOT NULL,
    AMOUNT DECIMAL(19,4) NOT NULL,
    NOTE VARCHAR(100) NOT NULL,
    TRANSACTION_DATE DATE NOT NULL
);